apiVersion: apps/v1
kind: Deployment # 类型为deployment
metadata: # deployment的详细信息
  name: example-http-server-deploy
  namespace: dev
spec: # deployment描述
  replicas: 1 # 每个pod生成3个副本
  selector: # 对标签为app=example-http-server-pod的pod进行操作
    matchLabels:
      app: example-http-server-pod
  template: # pod的模板设置
    metadata: # pod的详细信息
      labels: # 给pod打上标签app=example-http-server-pod
        app: example-http-server-pod
    spec: # pod描述
      restartPolicy: Always # pod重启策略，默认为Always
      containers: # 容器信息
        - name: example-http-server
          image: xudengtang/go-example:latest
          imagePullPolicy: Always # 设置镜像拉取策略
          env: # 设置环境变量
            - name: RUN_MODE
              value: "debug"
          command: ["/go-example", "http"] # 容器运行后执行命令
          ports: # 容器暴露端口
            - name: http-port
              containerPort: 8080
              protocol: TCP
            - name: http-pprof-port
              containerPort: 6060
              protocol: TCP
          volumeMounts: # 挂载目录
            - name: configs-volume
              mountPath: /configs/debug
            - name: jwt-certs-volume
              mountPath: /assets/certs/1652421664
            - name: grpc-certs-volume
              mountPath: /assets/certs/grpc_tls
            - name: logs-volume
              mountPath: /logs
            - name: nacos-volume
              mountPath: /nacos
      volumes: # 定义存储卷
        - name: configs-volume
          configMap:
            name: example-server-configmap
        - name: jwt-certs-volume
          secret:
            secretName: example-server-secret-jwt-certs
        - name: grpc-certs-volume
          secret:
            secretName: example-server-secret-grpc-certs
        - name: logs-volume
          hostPath:
            path: /Users/zonst/dockerVolumes/exampleVolume/http/logs/http
        - name: nacos-volume
          hostPath:
            path: /Users/zonst/dockerVolumes/exampleVolume/http/nacos/http



