server:
  http:
    name: "http"
    addr: ""
    port: "8080"
  http_pprof:
    name: "http_pprof"
    addr: ""
    port: "6060"
  socket:
    name: "socket"
    addr: ""
    port: "30000"
  grpc:
    name: "grpc"
    addr: ""
    port: "9090"

certs:
  curKey: 1652421664
  keys: [1652421664]

common:
  username: "小明"
  pwd: 123456

mysql:
  group:
    max_open: 20
    max_idle: 5
    max_lifetime: 10
    master:
      dsn: "root:root@tcp(192.168.200.200:3306)/go_example?charset=utf8mb4"
    slaves:
      - dsn: "root:root@tcp(192.168.200.200:3306)/go_example?charset=utf8mb4"
  single:
    dsn: "root:root@tcp(192.168.200.200:3306)/go_example?charset=utf8mb4"
    max_open: 20
    max_idle: 5
    max_lifetime: 10
redis:
  single:
    addr: "192.168.200.200:6379"
    password: ""
    db: 0
    pool_size: 20
  group:
    addrs:
      - 192.168.200.200:7000
      - 192.168.200.200:7001
      - 192.168.200.200:7002
      - 192.168.200.200:7003
      - 192.168.200.200:7004
      - 192.168.200.200:7005
    password: ""
    pool_size: 20
mongodb:
  # 格式：mongodb://username:password@addr1:port2,addr2:port2
  addr: "mongodb://192.168.200.200:27017"
  max_open: 20
consul:
  addr: "192.168.200.200:8500"
jenkins:
  host: "http://192.168.200.200:8088/"
  username: "jenkins"
  password: "1110ab88c3398a2d7ff470a7e9a8026d10"
cacheKeys:
  userInfo: "user_info:%d"


