server:
  http:
    name: "http"
    addr: ""
    port: "8080"
  http_pprof:
    name: "http_pprof"
    addr: ""
    port: "6060"
  socket:
    name: "socket"
    addr: ""
    port: "30000"
  grpc:
    name: "grpc"
    addr: ""
    port: "9090"

certs:
  cur_key: 1652421664
  keys: [1652421664]

common:
  socket_white_ip_list:
    - "192.168.80.100"
    - "192.168.163.*"
    - "10.0.98.*"
    - "10.1.0.1"

mysql:
  group:
    max_open: 20
    max_idle: 5
    max_lifetime: 10
    master:
      dsn: "root:root@tcp(192.168.80.100:3306)/go_example?charset=utf8mb4"
    slaves:
      - dsn: "root:root@tcp(192.168.80.100:3306)/go_example?charset=utf8mb4"
  single:
    dsn: "root:root@tcp(192.168.80.100:3306)/go_example?charset=utf8mb4"
    max_open: 20
    max_idle: 5
    max_lifetime: 10
redis:
  single:
    addr: "192.168.80.100:6379"
    password: ""
    db: 0
    pool_size: 20
  group:
    addrs:
      - 192.168.80.100:7000
      - 192.168.80.100:7001
      - 192.168.80.100:7002
      - 192.168.80.100:7003
      - 192.168.80.100:7004
      - 192.168.80.100:7005
    password: ""
    pool_size: 20
mongodb:
  # 格式：mongodb://username:password@addr1:port2,addr2:port2
  addr: "mongodb://192.168.80.100:27017"
  max_open: 20
consul:
  host: "192.168.80.100"
  port: "8500"
jenkins:
  host: "http://192.168.80.100:8088/"
  username: "jenkins"
  password: "2a9138c4fbb74ac0887155053ee1e191"
alibaba_sms:
  end_point: "dysmsapi.aliyuncs.com"
  access_key_id: "LTAI4GFM5Sqw5AiWwAPq4che"
  access_key_secret: "QfaWjC3BJkOJRP0v3ewntdOQi8nKVZ"
alibaba_sms_code:
  template_code: "SMS_204125567"
  sign_name: "小区闲置物品信息交流平台" # 短信签名
kafka:
  server_addr_list:
    - "192.168.80.100:9092"
    - "192.168.80.100:9093"
    - "192.168.80.100:9094"
  producer_config:
    ack: -1 # 0 不需要应答 1 leader应答 -1 leader和follower都需要应答
    partitioner_policy: # "hash" # hash、random、robin、manual；若为consum需要完善go-contrib包中的自定义分区器方法
    batch_message_num: 0 # 累计多少条消息打包发送
    linger_ms: 0 # 打包发送间隔时间
    message_max_bytes: 0 # 一条消息最大字节数，默认为1000000，约等于1M
    compression_type: 0 # 压缩方式 0 不压缩 1 zip压缩 2 Snappy压缩 3 LZ4压缩 4 ZSTD压缩
    idempotent_enabled: true # 是否开启幂等 要求ack=-1,max_open_requests=1,retry_max>0
    max_open_requests: 1 # 若开启幂等，这里要求设置为1（该包存在的问题暂未解决）
    retry_max: 3 # 发送失败重试次数
  consumer_config:
    group_id: "test12" # 消费者组id
    balance_strategy: "range" # 消费者组分区再平衡策略 range、roundrobin、sticky
    fetch_min_bytes: 1 # 每批次抓取数据最小字节数
    fetch_max_bytes: 0 # 每批次抓取数据最大字节数
    max_wait_time_ms: 500 # 每批次数据达到的超时时间（毫秒）
    from_beginning: true # 是否从0开始消费（貌似不起作用）
    offset_auto_commit_enabled: true # offset是否设置为自动提交
    offset_auto_commit_interval: 0 # offset自动提交的时间间隔
    max_poll_records: 500 # 一次拉取返回消息的最大条数
  consumer_reset_offset_config: # 指定offset消费
    enabled: false
    list:
      - topic: "second"
        partition: 0
        offset: 10
email:
  send_email: "1136728155@qq.com"
  host: "smtp.qq.com"
  port: 465
  account: "1136728155@qq.com"
  password: "dqheqwuqpqociieb"
sentry:
  dsn: "https://789e8b4d389e40c5994f6b09bd89d519@o435470.ingest.sentry.io/4504257001422848"
  server_name: "go_example"
  sample_rate: 1.0
  traces_sample_rate: 1.0
  attach_stacktrace: true
rabbitmq:
  dsn: "amqp://admin:admin@192.168.80.100:5672"