server:
  http:
    name: "http"
    addr: ""
    port: "8080"
  http_pprof:
    name: "http_pprof"
    addr: ""
    port: "6060"
  socket:
    name: "socket"
    addr: ""
    port: "30000"
  grpc:
    name: "grpc"
    addr: ""
    port: "9090"

certs:
  cur_key: 1652421664
  keys: [1652421664]

mysql:
  group:
    max_open: 20
    max_idle: 5
    max_lifetime: 10
    master:
      dsn: "root:root@tcp(192.168.200.200:3306)/go_example?charset=utf8mb4"
    slaves:
      - dsn: "root:root@tcp(192.168.200.200:3306)/go_example?charset=utf8mb4"
  single:
    dsn: "root:root@tcp(192.168.200.200:3306)/go_example?charset=utf8mb4"
    max_open: 20
    max_idle: 5
    max_lifetime: 10
redis:
  single:
    addr: "192.168.200.200:6379"
    password: ""
    db: 0
    pool_size: 20
  group:
    addrs:
      - 192.168.200.200:7000
      - 192.168.200.200:7001
      - 192.168.200.200:7002
      - 192.168.200.200:7003
      - 192.168.200.200:7004
      - 192.168.200.200:7005
    password: ""
    pool_size: 20
mongodb:
  # 格式：mongodb://username:password@addr1:port2,addr2:port2
  addr: "mongodb://192.168.200.200:27017"
  max_open: 20
consul:
  host: "127.0.0.1"
  port: "8500"
jenkins:
  host: "http://192.168.200.200:8088/"
  username: "jenkins"
  password: "1110ab88c3398a2d7ff470a7e9a8026d10"
alibaba_sms:
  end_point: "dysmsapi.aliyuncs.com"
  access_key_id: "LTAI4GFM5Sqw5AiWwAPq4che"
  access_key_secret: "QfaWjC3BJkOJRP0v3ewntdOQi8nKVZ"
alibaba_sms_code:
  template_code: "SMS_204125567"
  sign_name: "小区闲置物品信息交流平台" # 短信签名
kafka:
  server_addr_list:
    - "127.0.0.1:9092"
    - "127.0.0.1:9093"
    - "127.0.0.1:9094"
  producer_config:
    ack: -1 # 0 不需要应答 1 leader应答 -1 leader和follower都需要应答
    partitioner_policy: # "hash" # hash、random、robin、manual；若为consum需要完善go-contrib包中的自定义分区器方法
    batch_message_num: 0 # 累计多少条消息打包发送
    linger_ms: 0 # 打包发送间隔时间
    message_max_bytes: 0 # 一条消息最大字节数，默认为1000000，约等于1M
    compression_type: 0 # 压缩方式 0 不压缩 1 zip压缩 2 Snappy压缩 3 LZ4压缩 4 ZSTD压缩
    idempotent_enabled: true # 是否开启幂等 要求ack=-1,max_open_requests=1,retry_max>0
    max_open_requests: 1 # 若开启幂等，这里要求设置为1（该包存在的问题暂未解决）
    retry_max: 3 # 发送失败重试次数
  consumer_config:
    group_id: "test3" # 消费者组id
    balance_strategy: "range" # 消费者组分区再平衡策略 range、roundrobin、sticky
    fetch_min_bytes: 1 # 每批次抓取数据最小字节数
    fetch_max_bytes: 0 # 每批次抓取数据最大字节数
    max_wait_time_ms: 500 # 每批次数据达到的超时时间（毫秒）
    from_beginning: true # 是否从0开始消费
    offset_auto_commit_enabled: true # offset是否设置为自动提交
    offset_auto_commit_interval: 0 # offset自动提交的时间间隔
    max_poll_records: 500 # 一次拉取返回消息的最大条数
  consumer_reset_offset_config: # 指定offset消费
    enabled: false
    list:
      - topic: "first"
        partition: 1
        offset: 443
      - topic: "first"
        partition: 0
        offset: 477
      - topic: "first"
        partition: 2
        offset: 424

