server:
  http:
    name: "http"
    addr: ""
    port: "8080"
  socket:
    name: "socket"
    addr: ""
    port: "30000"
  grpc:
    name: "grpc"
    addr: ""
    port: "9090"

certs:
  curKey: 1652421664
  keys: [1652421664]

common:
  username: "小明"
  pwd: 123456

mysql:
  group:
    max_open: 20
    max_idle: 5
    max_lifetime: 10
    master:
      dsn: "root:root@tcp(127.0.0.1:3306)/go_example?charset=utf8mb4"
    slaves:
      - dsn: "root:root@tcp(127.0.0.1:3306)/go_example?charset=utf8mb4"
  single:
    dsn: "root:root@tcp(127.0.0.1:3306)/go_example?charset=utf8mb4"
    max_open: 20
    max_idle: 5
    max_lifetime: 10
redis:
  single:
    addr: "127.0.0.1:6379"
    password: "redis"
    db: 0
    pool_size: 20
  group:
    addrs:
      - 127.0.0.1:7000
      - 127.0.0.1:7001
      - 127.0.0.1:7002
      - 127.0.0.1:7003
      - 127.0.0.1:7004
      - 127.0.0.1:7005
    password: ""
    pool_size: 20
mongodb:
  # 格式：mongodb://username:password@addr1:port2,addr2:port2
  addr: "mongodb://127.0.0.1:27017"
  max_open: 20
consul:
  addr: "127.0.0.1:8500"
jenkins:
  host: "http://127.0.0.1:8088/"
  username: "admin"
  password: "11a8c7f5ad7e4d9bcbbe08eceb415eb7ad"
cacheKeys:
  userInfo: "user_info:%d"


