server:
  http:
    name: "http"
    addr: ""
    port: "8080"
  socket:
    name: "socket"
    addr: ""
    port: "30000"
  grpc:
    name: "grpc"
    addr: ""
    port: "9090"

certs:
  curKey: 1652421664
  keys: [1652421664]

common:
  username: "小明"
  pwd: 123456

mysql:
  group:
    master:
      dsn: "root:root@tcp(192.168.163.130:3306)/go_example?charset=utf8mb4"
    slaves:
      - dsn: "root:root@tcp(192.168.163.131:3306)/go_example?charset=utf8mb4"
  single:
    dsn: "root:root@tcp(192.168.163.131:3306)/go_example?charset=utf8mb4"
redis:
  single:
    addr: "192.168.163.131:6379"
    password: "redis"
    db: 0
  group:
    addrs:
      - 192.168.163.131:7000
      - 192.168.163.131:7001
      - 192.168.163.131:7002
      - 192.168.163.131:7003
      - 192.168.163.131:7004
      - 192.168.163.131:7005
    password: ""
mongodb:
  single:
    addr: "192.168.163.131:27017"
    username: ""
    password: ""
    max_open: 10
consul:
  addr: "192.168.163.131:8500"
cacheKeys:
  userInfo: "user_info:%d"


